[env:esp32-s3-box-3b]
platform = espressif32
board = esp32s3box
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs
board_build.partitions = default_16MB.csv
board_build.flash_mode = dio
build_flags =
    -DCORE_DEBUG_LEVEL=0
    -DLGFX_AUTODETECT
build_src_filter = +<*> +<buddies/>
lib_deps =
    lovyan03/LovyanGFX @ ^1.2.7
    bodmer/TFT_eSPI @ ^2.5.43
    bitbank2/AnimatedGIF @ ^2.1.1
    bblanchon/ArduinoJson @ ^7.0.0
